<html>

<div style="max-width: 800px; margin: 0 auto; padding: 20px;">

<div style="background-color: rgba(255, 255, 255, 0.9); padding: 20px;">
<title>2026年桌球夏令營報名表</title>
<center><width =50%>
<head><h1>2026 乒乓小將・桌球主題夏令營報名表(7/15-7/23)</h1></head>
<body style="
    background-image: url('https://media.istockphoto.com/id/165817342/zh/%E5%90%91%E9%87%8F/table-tennis.jpg?s=1024x1024&w=is&k=20&c=REb-sQf8X6j5rgcla1rMDKRkiYH1H_AkOceLH0vx3Nw='); 
    background-size: cover;       
    background-attachment: fixed; 
    background-position: center;  ">



<p>在這個暑假，讓孩子放下手機，踏上球場！桌球不僅是一項運動，更是訓練手眼協調、反應速度與抗壓能力的最佳途徑。我們的夏令營結合專業教練團與趣味課程設計，帶領孩子從零開始，感受打球的快樂
</p>
<hr>
活動亮點
<UL>
<LI>由<b>國手級或專業教練</b>親自示範，從正確握拍到發球技巧，建立紮實基礎。
<LI>針對初學者與進階學員<b>進行分組</b>確保每位孩子都能在適合的進度中成長。
<LI>引進發球機輔助，針對性加強正手、反手與步法訓練。
<LI>每日安排創意小遊戲與結業對抗賽，讓學習不再枯燥。
</UL>
<p>
<br>
<div style="max-width: 600px; margin: auto; border: 1px solid black; padding: 20px;">
<table style="width: 100%; border-spacing: 10px; border-collapse: separate;">
    <tr>
        <td>上午時段</td>
        
        <td>基本功養成</td>
        
        <td>握拍、站位、平擊球基礎訓練</td>
        
    </tr>
    <tr>
        <td>午餐休息</td>
        
        <td>靜態交流</td>
        
        <td>運動營養知識、球星經典賽事賞析</td>
        
    </tr>
    <tr>
        
        <td>下午時段</td>
        
        <td>實戰與步法</td>
        
        <td>多球練習、移位步法、旋轉球解析</td>
    </tr>
    <tr>
       
        <td>最後衝刺</td>
        
        <td>趣味挑戰賽</td>
        
        <td>團體接力、分組積分對抗賽</td>
    </tr>
</table>
</div>
<form>
<p>你的姓名</p><input type="text" placeholder="請輸入姓名">
<input type ="radio" name="gender">男
<input type ="radio" name="gender">女
<br>
<p>你的密碼</p><input type="password" placeholder="請輸入密碼">
<br>
<p>你的email</p><input type="email" placeholder="請輸入email">
<br>
<p>請問球齡幾年</p><input type="number">
<br>
<p>請問年齡幾歲</p><input type="number">
<br>
<p>您的職業</p>
<select>
  <option>學生</option>
  <option>老師</option>
  <option>工程師</option>
  <option>醫生</option>
  <option>工人</option>
  <option>公務員</option>
  <option>其他</option>
</select>
<p>如何以及何時得知此活動</p>
<select>
  <option>網路</option>
  <option>朋友介紹</option>
  <option>宣傳單</option>
</select>
<input type ="date">
<br>
<br>
上述資料皆誠實填寫<input type="checkbox">
<br>
<br>
<input type="reset" value="重新填寫">
<input type="submit" value="送出報名">
</form>

</center>
</width>
</div>
</div>
</body>
</html>

